import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Toolbar } from "@/core/components";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full w-full`} >
        <div className="h-full w-full grid grid-rows-[auto_1fr]">
          <Toolbar />
          <main className="flex flex-col gap-8 items-center justify-center h-full w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
